version: "3"

services:
  postgres:
    image: "postgres:9.6.17"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/blu
      - gems:/gems
 

volumes:
  postgres:
  gems: