default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: blu_development

test:
  <<: *default
  database: blu_depth_test
 

production:
  <<: *default
  database: blu_production
  username: blu
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>